export const EMOTION_MAP: Record<string, string> = {
  happy: '开心',
  delight: '愉悦',
  neutral: '一般',
  sad: '难过',
  angry: '愤怒',
  irritable: '烦躁',
  anxious: '焦虑',
  calm: '平静',
  excited: '兴奋',
  tired: '疲惫',
  grateful: '感恩',
  ecstasy: '狂喜',
  admiration: '钦佩',
  fear: '恐惧',
  amazement: '惊愕',
  disgust: '厌恶',
  vigilance: '警惕',
  trust: '信任',
  surprise: '惊喜',
  loathing: '反感',
  anticipation: '期待',
  acceptance: '接纳',
  distraction: '娱乐',
  pensiveness: '沉思',
  boredom: '无聊',
  annoyance: '烦恼',
  interest: '兴趣',
  rage: '生气',
  terror: '害怕',
  apprehension: '忧虑',
  grief: '悲伤',
  disapproval: '反对',
  remorse: '悔恨',
  contempt: '蔑视',
}

export const EMOTION_OPTIONS = Object.entries(EMOTION_MAP).map(([value, label]) => ({
  value,
  label,
}))