CREATE TABLE mood_tags (
  mood_id INT UNSIGNED NOT NULL,
  tag_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (mood_id, tag_id),
  CONSTRAINT fk_mood_tags_mood FOREIGN KEY (mood_id) REFERENCES moods (id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT fk_mood_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
